### ISSUE TITLE
Using NSMutableDictionary instead of NSDictionary

### ISSUE THREAD

**Issue by ksenks** [googlesamples/io2015-codelabs#14]
In lab manual "Add Analytics Code to your app", in part related with PatternViewController.m
the user creates NSMutableDictionary, where it's better to create immutable version (NSDictionary). The code with NSDictionary is compiled and works. 
![screen shot 2015-05-29 at 11 39 28 am](https://cloud.githubusercontent.com/assets/1662825/7889924/6e8bf072-05f7-11e5-8d24-b841b5770b61.png)

**Comment by ToddKerpelman** [comment]
Hmmm... not sure about this one. For learning purposes, it's probably good for folks to understand that GAIDictionaryBuilder returns an NSMutableDictionary. 

Also, I'm not sure casting it as a NSDictionary will change the fact that underneath it's still an NSMutableDict. If you add this line under your modified code...

  NSLog(@"Event is mutable dictionary? %d", [event isKindOfClass:[NSMutableDictionary class]]);

you'll see that it's still considered an NSMutableDictionary by iOS.

On the other hand, if your bug is really suggesting that the API is wrong and it should be returning a dictionary instead of a mutable dict, that's another matter. :) I don't know how often we expect developers to make calls that would modify this thing after the fact...

**Comment by samthor** [comment]
I'm going to close this one as fine. The Analytics docs (not just the codelab) suggest using `NSMutableDictionary` since that's the real type.

**Comment by ksenks** [comment]
@ToddKerpelman I don't see reasons why the code can not look like this:

NSDictionary *event =
    [[[GAIDictionaryBuilder createEventWithCategory:@"Action"
                                            action:@"Share"
                                             label:nil
                                             value:nil] build] copy];
[tracker send:event];

This is more understandable and safe.

**Comment by ToddKerpelman** [comment]
That's a fair point. 

I actually think this probably points to a larger issue, which is: should this be a mutable dictionary in the first place? It all depends on whether or not the developer is ever meant to change things with it afterwards. (Or if it's a requirement from the library because it needs to somehow mutate it afterwards.) If not, maybe the right solution would be to file a bug and just have this method return an NSDictionary.

**Comment by ToddKerpelman** [comment]
FWIW, I'm bringing this up with the Analytics SDK team to see what they have to say.
